defaults:
  - base

data:
  cluster_path: null

diffuser:
  so3:
    use_cached_score: True

  
experiment:
  name: vfn_v11_full_4_4090
  num_epoch: 95
  batch_size: 128
  max_squared_res: 300000
  rot_loss_t_threshold: 0.0
  rot_loss_weight: 1.0
  separate_rot_loss: False
  sample_mode: time_batch
  num_gpus: 4
  use_ddp : True
  num_loader_workers: 64

hydra:
  sweeper:
    params:
